### ISSUE TITLE
Home Page not available

### ISSUE THREAD

**Issue by wizardpisces** [selemondev/spark-ui#77]
Home Page not available
https://spark-ui-dev.vercel.app/

**Comment by wizardpisces** [comment]
<img width="855" alt="image" src="https://github.com/user-attachments/assets/263168f9-35a7-4eb7-8234-a252f0fa6b6c">

**Comment by RamonDonadeu** [comment]
It works for me

**Comment by selemondev** [comment]
Hey @wizardpisces, try this url: https://spark-ui.dev/
